export default {
  login: "jonasschmedtmann",
  id: 18718850,
  node_id: "MDQ6VXNlcjE4NzE4ODUw",
  avatar_url: "https://avatars.githubusercontent.com/u/18718850?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/jonasschmedtmann",
  html_url: "https://github.com/jonasschmedtmann",
  followers_url: "https://api.github.com/users/jonasschmedtmann/followers",
  following_url:
    "https://api.github.com/users/jonasschmedtmann/following{/other_user}",
  gists_url: "https://api.github.com/users/jonasschmedtmann/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/jonasschmedtmann/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/jonasschmedtmann/subscriptions",
  organizations_url: "https://api.github.com/users/jonasschmedtmann/orgs",
  repos_url: "https://api.github.com/users/jonasschmedtmann/repos",
  events_url: "https://api.github.com/users/jonasschmedtmann/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/jonasschmedtmann/received_events",
  type: "User",
  site_admin: false,
  name: "Jonas Schmedtmann",
  company: null,
  blog: "jonas.io",
  location: "Faro, Portugal",
  email: null,
  hireable: null,
  bio: "Designer. Developer. Online teacher.",
  twitter_username: "jonasschmedtman",
  public_repos: 5,
  public_gists: 1,
  followers: 13160,
  following: 0,
  created_at: "2016-04-28T11:17:03Z",
  updated_at: "2022-07-06T13:36:54Z",
};
