export default {
  login: "AndrewShmorhunGit",
  id: 103834523,
  node_id: "U_kgDOBjBjmw",
  avatar_url: "https://avatars.githubusercontent.com/u/103834523?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/AndrewShmorhunGit",
  html_url: "https://github.com/AndrewShmorhunGit",
  followers_url: "https://api.github.com/users/AndrewShmorhunGit/followers",
  following_url:
    "https://api.github.com/users/AndrewShmorhunGit/following{/other_user}",
  gists_url: "https://api.github.com/users/AndrewShmorhunGit/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/AndrewShmorhunGit/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/AndrewShmorhunGit/subscriptions",
  organizations_url: "https://api.github.com/users/AndrewShmorhunGit/orgs",
  repos_url: "https://api.github.com/users/AndrewShmorhunGit/repos",
  events_url: "https://api.github.com/users/AndrewShmorhunGit/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/AndrewShmorhunGit/received_events",
  type: "User",
  site_admin: false,
  name: "Andrew Shmorhun",
  company: "No company :(",
  blog: "",
  location: "Kiev",
  email: null,
  hireable: null,
  bio: "Beginner in JavaScript development 🙂",
  twitter_username: null,
  public_repos: 8,
  public_gists: 0,
  followers: 0,
  following: 2,
  created_at: "2022-04-16T13:20:32Z",
  updated_at: "2022-08-15T07:00:05Z",
};
